source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 7.0'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 6.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Load environment variables from .env file
  gem 'dotenv-rails'
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]




# --- Authentication ---
gem "bcrypt", "~> 3.1.20"             # For password hashing (already using)

gem 'jwt', '~> 2.7'                  # For token-based authentication (JWT)

# --- Google OAuth2 via Omniauth ---
gem 'omniauth', '~> 2.1'                       # Base gem for OmniAuth
gem 'omniauth-rails_csrf_protection', '~> 1.0' # CSRF protection for OmniAuth
gem 'omniauth-google-oauth2', '~> 1.1'         # Google OAuth2 strategy for OmniAuth

# --- Music Platform OAuth ---
gem 'omniauth-spotify', '~> 0.0.13'            # Spotify OAuth2 strategy for OmniAuth
gem 'rspotify', '~> 2.12'                      # Spotify Web API wrapper
# gem 'omniauth-soundcloud', '~> 1.0'          # SoundCloud OAuth (version conflict with rspotify)
